version: "3.9"

services: 
  mongo_logs:
    image: mongo
    container_name: mongo_logs
    restart: always
    ports:
      - "27017:27017"
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: docker
      # MONGO_INITDB_ROOT_PASSWORD: docker
    volumes:
      - mongo-volume:/data/db

  api: 
    build: .
    container_name: api_logs
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links:
      - mongo_logs
    depends_on:
      - mongo_logs


volumes: 
  mongo-volume: 
    driver: local
