version: "3.9"

services: 
  mongo_logs:
    image: mongo
    container_name: mongo_logs
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db

  redis_logs:
    image: 'bitnami/redis'
    container_name: redis_logs
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=true

  api: 
    build: .
    container_name: api_logs
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links:
      - mongo_logs
    depends_on:
      - mongo_logs


volumes: 
  mongo-volume: 
    driver: local
